task: classification
model:
  name: inception
  params:
    num_classes: 1
    pretrained: true
    aux_logits: true
loss: bce_with_logits
optimizer:
  name: adam
  lr: 0.001
metrics:
  accuracy:
    task: binary
  precision:
    task: binary
  recall:
    task: binary
  mcc:
    task: binary
  cohen_kappa:
    task: binary
batch_size: 64
train:
  epochs: 1
  inputs: data/FloodNet_dataset/train/image
  targets: data/flood_train_rel_paths.csv
val:
  inputs: data/FloodNet_dataset/val/image
  targets: data/flood_val_rel_paths.csv
test:
  inputs: data/FloodNet_dataset/test/image
  targets: data/flood_test_rel_paths.csv
