task: segmentation
model:
  name: pspnet
  params:
    num_classes: 10
    pretrained: true
loss: multiclass_dice
optimizer:
  name: adam
  lr: 0.001
metrics:
  accuracy:
    task: multiclass
    num_classes: 10
  precision:
    task: multiclass
    num_classes: 10
  recall:
    task: multiclass
    num_classes: 10
  mcc:
    task: multiclass
    num_classes: 10
  cohen_kappa:
    task: multiclass
    num_classes: 10
  iou:
    task: multiclass
    num_classes: 10
    average: macro
batch_size: 1
train:
  epochs: 1
  inputs: dataset/FloodNet_dataset/train/image
  targets: dataset/FloodNet_dataset/train/label
val:
  inputs: dataset/FloodNet_dataset/val/image
  targets: dataset/FloodNet_dataset/val/label
test:
  inputs: dataset/difficults_test/image6
  targets: dataset/difficults_test/label6
