model: inception
num_classes: 1
pretrained: true
aux_logits: true
loss: bce_with_logits
optimizer:
  name: adam
  lr: 0.001
metrics:
  accuracy:
    task: binary
    num_classes: 1
  recall:
    task: multiclass
    num_classes: 10
train:
  epochs: 10
  batch_size: 64
