model:
  name: inception
  params:
    num_classes: 1
    pretrained: true
    aux_logits: true
loss: dice
optimizer:
  name: adam
  lr: 0.001
metrics:
  accuracy:
    task: binary
  precision:
    task: binary
  recall:
    task: binary
  mcc:
    task: binary
  cohen_kappa:
    task: binary
train:
  epochs: 10
  batch_size: 64
